artifacts root: artifacts


data_ingestion:
  root dir: artifacts/data_ingestion
  source_URL: https://github.com/heysourin/Machine-Learning-Projects/raw/main/wine.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
